export const CORS_HEADERS = {
  "Access-Control-Allow-Methods": "GET, HEAD, OPTIONS",
  "Access-Control-Allow-Origin": "*",
  "Cross-Origin-Resource-Policy": "cross-origin",
} as const;

interface ProfileLink {
  readonly href: string;
  readonly rel: string;
  readonly type: string;
}

const profilePageRel = "https://webfinger.net/rel/profile-page";

const profileLinks: readonly ProfileLink[] = [
  "https://www.7cups.com/@mynameistito",
  "https://8tracks.com/mynameistito",
  "https://www.9gag.com/u/mynameistito",
  "https://about.me/mynameistito",
  "https://independent.academia.edu/mynameistito",
  "https://airbit.com/mynameistito",
  "https://www.alik.cz/u/mynameistito",
  "https://allmylinks.com/mynameistito",
  "https://anilist.co/user/mynameistito/",
  "https://discussions.apple.com/profile/mynameistito",
  "https://archive.org/details/@mynameistito",
  "https://www.artstation.com/mynameistito",
  "https://asciinema.org/~mynameistito",
  "https://bandcamp.com/mynameistito",
  "https://www.behance.net/mynameistito",
  "https://bento.me/mynameistito",
  "https://bio.site/mynameistito",
  "https://bitbucket.org/mynameistito/",
  "https://bsky.app/profile/mynameistito.com",
  "https://bsky.app/profile/mynameistito.bsky.social",
  "https://buymeacoffee.com/mynameistito",
  "https://campsite.bio/mynameistito",
  "https://cara.app/mynameistito/all",
  "https://www.chess.com/member/mynameistito",
  "https://www.clippings.me/mynameistito",
  "https://www.codecademy.com/profiles/mynameistito",
  "https://codepen.io/mynameistito",
  "https://counter.social/@mynameistito",
  "https://www.dailymotion.com/mynameistito",
  "https://dev.to/mynameistito",
  "https://mynameistito.deviantart.com",
  "https://dmoj.ca/user/mynameistito",
  "https://www.facebook.com/profile.php?id=100080348198696",
  "https://fameswap.com/user/mynameistito",
  "https://figma.com/@mynameistito",
  "https://www.fiverr.com/mynameistito",
  "https://www.freelancer.com/u/mynameistito",
  "https://www.furaffinity.net/user/mynameistito/",
  "https://genius.com/mynameistito",
  "https://mynameistito.getform.com",
  "https://gitee.com/mynameistito",
  "https://www.github.com/mynameistito",
  "https://gitlab.com/mynameistito",
  "https://en.gravatar.com/mynameistito",
  "https://mynameistito.gumroad.com",
  "https://huggingface.co/mynameistito",
  "https://icq.im/mynameistito",
  "https://imgur.com/user/mynameistito",
  "https://instagram.com/mynameistito_",
  "https://interpals.net/mynameistito",
  "https://keybase.io/mynameistito",
  "https://kick.com/mynameistito",
  "https://lichess.org/@/mynameistito",
  "https://linkin.bio/mynameistito",
  "https://linktr.ee/mynameistito",
  "https://aus.social/@mynameistito",
  "https://infosec.exchange/@mynameistito",
  "https://mas.to/@mynameistito",
  "https://mastodon.nz/@mynameistito",
  "https://mastodon.social/@mynameistito",
  "https://medium.com/@mynameistito",
  "https://www.mixcloud.com/mynameistito/",
  "https://my.bio/mynameistito",
  "https://mylinks.ai/mynameistito",
  "https://opensea.io/mynameistito",
  "https://onlyfans.com/mynameistito",
  "https://patreon.com/mynameistito",
  "https://mynameistito.picfair.com/",
  "https://pinterest.com/mynameistito",
  "https://www.polywork.com/mynameistito",
  "https://www.producthunt.com/@mynameistito",
  "https://shor.by/mynameistito",
  "https://signal.me/#eu/QVuzgFH6OCw75cHmvkq4k5jsbWz_jnrRphaUAueUdF5olInuFOBO4rhPbBX1OJcS",
  "https://solo.to/mynameistito",
  "https://soundcloud.com/my-name-is-tito",
  "https://open.spotify.com/user/31rjwiyrgqflubxlfduas2gzagku?si=19efa75fabb94868&nd=1&dlsi=3cd0be7c6d4e4893",
  "https://mynameistito.substack.com",
  "https://substack.com/@mynameistito",
  "https://taplink.cc/mynameistito",
  "https://t.me/mynameistito",
  "https://tellonym.me/mynameistito",
  "https://www.threads.net/@mynameistito_",
  "https://trible.com/mynameistito",
  "https://truthsocial.com/@mynameistito",
  "https://unsplash.com/@mynameistito",
  "https://vimeo.com/mynameistito",
  "https://x.com/mynameistito",
  "https://www.xda-developers.com/members/mynameistito.1234567/",
  "https://www.xing.com/profile/mynameistito",
  "https://www.xbox.com/en-NZ/play/user/MyNameIsTito",
  "https://www.pixiv.net/en/users/111440379",
].map((href) => ({ href, rel: profilePageRel, type: "text/html" }));

export const webfinger = {
  aliases: ["https://mynameistito.com"],
  links: profileLinks,
  subject: "acct:contact@mynameistito.com",
} as const;

export const webfingerJson = {
  ...webfinger,
  links: [
    ...profileLinks,
    {
      href: "https://doras.to/mynameistito",
      rel: profilePageRel,
      type: "text/html",
    },
  ],
};
